routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// })->name('/');

Route::get('/', [HomeController::class, 'index'])->name('home');



Auth::routes(['verify' => true]);

Route::prefix('admin')
->middleware(['auth', 'check.admin'])
->group(function () {
    Route::get('/login', function () {
        return redirect('/login');
    });

    Route::resource('products', ProductController::class);
    Route::resource('categories', CategoryController::class);
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'id',
        'name',
        'category_id',
        'price',
        'amount',
        'filepath',
        'status',
    ];

    public function getCategoryNameAttribute()
    {
        return $this->category->name;
    }

    public function getStatusAttribute($status)
    {
        return $status ? 'Active' : 'Inactive';
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateProductRequest;
use App\Http\Requests\UpdateProductRequest;
use App\Services\CategoryService;
use App\Services\ProductService;

class ProductController extends Controller
{
    protected $productService;
    protected $categoryService;

    public function __construct(ProductService $productService, CategoryService $categoryService)
    {
        $this->productService = $productService;
        $this->categoryService = $categoryService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = $this->productService->getAll();
        return view('backEnd.products.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = $this->categoryService->getAll();
        return view('backEnd.products.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateProductRequest $request)
    {
        $data = $request->validated();
        $this->productService->create($data);
        return redirect()->route('products.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = $this->productService->getById($id);
        return view('backEnd.products.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categories = $this->categoryService->getAll();
        $product = $this->productService->getById($id);
        return view('backEnd.products.edit', compact('product', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateProductRequest $request, $id)
    {
        $data = $request->validated();
        $this->productService->update($id, $data);
        return redirect()->route('products.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->productService->delete($id);
        return redirect()->route('products.index');
    }
}

resources/views/backEnd/products/create.blade.php
@extends('layouts.backEnd.app')
@section('content')

<form action="{{ route('products.store') }}" method="POST" class="container cr-up-form" enctype="multipart/form-data">

    @csrf
    <p class="form-name">Create product</p>

    <div class="form-group">
        <label for="name" class="required">Name of product</label>
        <input type="text" class="form-control input-name" id="name" name="name" required>
    </div>

    <div class="form-group">
        <label for="category_id" class="required">Category</label>
        <select class="form-control input-name" id="category_id" name="category_id" required>
            <option hidden selected></option>
            @foreach ($categories as $category)
            <option value="{{$category->id}}">{{$category->name}}</option>
            @endforeach
        </select>
    </div>

    <div class="amount-price">
        <div class="form-group">
            <label for="price">Price</label>
            <input type="text" class="form-control input-name amount" id="price" name="price">
        </div>
        <div>
            <label for="amount">Amount</label>
            <input type="text" class="form-control input-name price" id="amount" name="amount">
        </div>
    </div>

    <div class="form-group">
        <label for="image">Image of product</label>
        <input type="file" class="form-control input-name" id="image" name="image">
    </div>

    <div class="form-group check-status">
        <input type="checkbox" class="status" name="status" value="1"> Active
    </div>

    <div class="form-group container can-sub-btn">
        <a href="{{ route('products.store') }}" class="btn can-btn">Cancel</a>
        <button type="submit" class="btn btn-primary add-btn">
            Submit
        </button>
    </div>
</form>

@endsection

resources/views/backEnd/products/edit.blade.php
@extends('layouts.backEnd.app')
@section('content')

<form action="{{ route('products.update', ['product' => $product->id]) }}" method="POST" class="container cr-up-form" enctype="multipart/form-data">

    @csrf
    <p class="form-name">Edit product</p>

    <div class="form-group">
        <label for="name" class="required">Name of product</label>
        <input type="text" class="form-control input-name" id="name" name="name" value="{{$product->name}}" required>
    </div>

    <div class="form-group">
    <label for="category_id" class="required">Category</label>
        <select class="form-control input-name" id="category_id" name="category_id" required>
            <option hidden selected value="{{$product->category_id}}">{{$product->categoryName}}</option>
            @foreach ($categories as $category)
            <option value="{{$category->id}}">{{$category->name}}</option>
            @endforeach
        </select>
    </div>

    <div class="amount-price">
        <div class="form-group">
            <label for="price">Price</label>
            <input type="text" class="form-control input-name amount" id="price" name="price" value="{{$product->price}}" />
        </div>
        <div>
            <label for="amount">Amount</label>
            <input type="text" class="form-control input-name price" id="amount" name="amount" value="{{$product->amount}}" />
        </div>
    </div>

    <div class="form-group">
        <label for="image">Image of product</label>
        <input type="file" class="form-control input-name" id="image" name="image" />
    </div>

    <div class="form-group check-status">
        @if ($product->status == 'Active')
        <input class="status" type="checkbox" name="status" value="1" checked> Active
        @else
        <input class="status" type="checkbox" name="status" value="1"> Active
        @endif
    </div>

    <div class="form-group container can-sub-btn">
        <a href="{{ route('products.index') }}" class="btn can-btn">Cancel</a>
        <button type="submit" class="btn btn-primary add-btn">
            Submit
            @csrf
            @method('PUT')
        </button>
    </div>
</form>

@endsection

resources/views/backEnd/products/index.blade.php
@extends('layouts.backEnd.app')
@section('content')

<div class="container">
    <div class="container head-table">
        <div class="table-name">
            List of products
        </div>
        <div>
            <div>
                <a href="{{ route('products.create') }}" class="btn btn-primary add-btn">Add new product</a>
            </div>
        </div>
    </div>

    <div class="body-table">
        <table class="table container ctn-content">
            <thead>
                <tr>
                    <th> ID </th>
                    <th> Name of product </th>
                    <th> Status </th>
                    <th> Active </th>
                </tr>
            </thead>
            <tbody>
                @foreach($products as $product)
                <tr>
                    <td class="text-left col-2">{{$product->id}}</td>
                    <td class="text-left col-6">{{$product->name}}</td>
                    <td class="text-left col-2 {{$product->status}}">{{$product->status}}</td>
                    <td class="text-left col-2 ed-btn">
                        <a href="{{ route('products.edit', ['product' => $product->id]) }}" class="edit-btn">Edit</a>
                        <form action="{{ route('products.destroy', ['product' => $product->id]) }}" method="post">
                            <button type="submit" class="delete-btn" onclick="return confirm('Are you sure you want to delete this item?')">
                                Delete
                                @csrf
                                @method('DELETE')
                            </button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>

@endsection