routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// })->name('/');

Route::get('/', [HomeController::class, 'index'])->name('home');



Auth::routes(['verify' => true]);

Route::prefix('admin')
->middleware(['auth', 'check.admin'])
->group(function () {
    Route::get('/login', function () {
        return redirect('/login');
    });

    Route::resource('products', ProductController::class);
    Route::resource('categories', CategoryController::class);
});

resources/views/layouts/backEnd/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Category management page</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>

    <link href="{{ asset('css/list.css') }}" rel="stylesheet">
</head>


<body>

    @include('layouts.backEnd.header')
    <div>
        @yield('content')
    </div>
</body>

</html>

resources/views/layouts/backEnd/header.blade.php
<!-- Scripts -->
<script src="{{ asset('js/app.js') }}" defer></script>

<div class="menu">
    <a class="navbar-brand nav-link" href="{{ url('/') }}">
        {{ config('app.name', 'Laravel') }}
    </a>
    <div class="container ctn-menu">
        <a class="col-4 menu-item" href="{{ route('categories.index') }}"> MANAGER CATEGORIES</a>
        <a class="col-4 menu-item" href="{{ route('products.index') }}">MANAGER PRODUCTS</a>
    </div>

    <div id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto">
            <li class="nav-item dropdown">
                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                    {{ Auth::user()->name }}
                </a>

                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                        {{ __('Logout') }}
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                        @csrf
                    </form>
                </div>
            </li>
        </ul>
    </div>
</div>