routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// })->name('/');

Route::get('/', [HomeController::class, 'index'])->name('home');



Auth::routes(['verify' => true]);

Route::prefix('admin')
->middleware(['auth', 'check.admin'])
->group(function () {
    Route::get('/login', function () {
        return redirect('/login');
    });

    Route::resource('products', ProductController::class);
    Route::resource('categories', CategoryController::class);
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'id',
        'name',
        'status',
    ];

    public function getStatusAttribute($status)
    {
        return $status ? 'Active' : 'Inactive';
    }
    
    public function products()
    {
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateCategoryRequest;
use App\Http\Requests\UpdateCategoryRequest;
use App\Services\CategoryService;

class CategoryController extends Controller
{
    protected $categoryService;

    public function __construct(CategoryService $categoryService)
    {
        $this->categoryService = $categoryService;
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = $this->categoryService->getAll();
        return view('backEnd.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backEnd.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateCategoryRequest $request)
    {
        $data = $request->validated();
        $this->categoryService->create($data);
        return redirect()->route('categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = $this->categoryService->getById($id);
        return view('backEnd.categories.index', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = $this->categoryService->getById($id);
        return view('backEnd.categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCategoryRequest $request, $id)
    {
        $data = $request->validated();
        $this->categoryService->update($id, $data);
        return redirect()->route('categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = $this->categoryService->delete($id);
        // dd($category->id);
        return redirect()->route('categories.index');
    }
}

resources/views/backEnd/categories/create.blade.php
@extends('layouts.backEnd.app')
@section('content')

<form action="{{ route('categories.store') }}" method="POST" class="container cr-up-form">

    @csrf
    <p class="form-name">Create category</p>

    <div class="form-group">
        <label for="name" class="required">Name of category</label>
        <input type="text" class="form-control input-name" id="name" name="name" required>
    </div>

    <div class="form-group check-status">
        <input class="status" type="checkbox" name="status" value="1">&nbsp; Active
    </div>

    <div class="form-group container can-sub-btn">
        <a href="{{ route('categories.index') }}" class="btn can-btn">Cancel</a>
        <button type="submit" class="btn btn-primary add-btn">
            Submit
            @method('POST')
        </button>
    </div>
</form>

@endsection

resources/views/backEnd/categories/edit.blade.php
@extends('layouts.backEnd.app')
@section('content')

<form action="{{ route('categories.update', ['category' => $category->id]) }}" method="POST" class="container cr-up-form">

    @csrf
    <p class="form-name">Edit category</p>

    <div class="form-group">
        <label for="name" class="required">Name of category</label>
        <input type="text" class="form-control input-name" id="name" value="{{$category->name}}" name="name" required/>
    </div>

    <div class="form-group check-status">
        @if ($category->status == 'Active')
            <input class="status" type="checkbox" name="status" value="1" checked> Active
        @else
            <input class="status" type="checkbox" name="status" value="1"> Active
        @endif
    </div>

    <div class="form-group container can-sub-btn">
        <a href="{{ route('categories.index') }}" class="btn can-btn">Cancel</a>
        <button type="submit" class="btn btn-primary add-btn">
            Submit
            @method('PUT')
        </button>
    </div>
</form>

@endsection

resources/views/backEnd/categories/index.blade.php
@extends('layouts.backEnd.app')
@section('content')

<div class="container">
    <div class="container head-table">
        <div class="table-name">
            List of categories
        </div>
        <div>
            <div>
                <a href="{{ route('categories.create') }}" class="btn btn-primary add-btn">Add new category</a>
            </div>
        </div>
    </div>

    <div class="body-table">
        <table class="table container ctn-content">
            <thead>
                <tr>
                    <th> ID </th>
                    <th> Name of category </th>
                    <th> Status </th>
                    <th> Active </th>
                </tr>
            </thead>
            <tbody>
                @foreach($categories as $category)
                <tr>
                    <td class="text-left col-2">{{$category->id}}</td>
                    <td class="text-left col-6">{{$category->name}}</td>
                    <td class="text-left col-2 {{$category->status}}">{{$category->status}}</td>
                    <td class="text-left col-2 ed-btn">
                        <a href="{{ route('categories.edit', ['category' => $category->id]) }}" class="edit-btn">Edit</a>
                        <form action="{{route('categories.destroy', ['category' => $category->id])}}" method="post">
                            <button type="submit" class="delete-btn" onclick="return confirm('Are you sure you want to delete this item?')">
                                Delete
                                @csrf
                                @method('DELETE')
                            </button>
                        </form>

                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>

@endsection